---

- name: Install any necessary dependencies [Debian/Ubuntu]
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - alien
  when: ansible_os_family == "Debian"

- name: get telegraf rpm
  # binary should be in S3, i.e.: s3://{{cfn_bucket}}/bin/telegraf/
  shell: "aws s3 cp {{telegraf_install_s3_path}} /tmp/telegraf.rpm"

- name: install rpm [Debian/Ubuntu]
  shell: alien -i /tmp/telegraf.rpm
  when: ansible_os_family == "Debian"

- name: install rpm [RedHat/CentOS]
  yum:
    name: /tmp/telegraf.rpm
    state: present
  when: ansible_os_family == "RedHat"
