---
- name: add influx repo [Debian/Ubuntu]
  shell: |
    # influxdata-archive_compat.key GPG Fingerprint: 9D539D90D3328DC7D6C8D3B9D8FF8E1F7DF8B07E
    curl -s https://repos.influxdata.com/influxdata-archive_compat.key > influxdata-archive_compat.key
    echo '393e8779c89ac8d958f81f942f9ad7fb82a25e133faddaf92e15b16e6ac9ce4c influxdata-archive_compat.key'\
    | sha256sum -c && cat influxdata-archive_compat.key\
    | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg > /dev/null
    echo 'deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg] https://repos.influxdata.com/debian stable main'\
    | sudo tee /etc/apt/sources.list.d/influxdata.list
    apt-get update
  when: telegraf_install_url is undefined or not telegraf_install_url
  changed_when: false

# by some reason update_cache flag doesn't work well
- name: Install Telegraf packages [Debian/Ubuntu]
  apt:
    name: telegraf
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: telegraf_install_url is undefined or not telegraf_install_url
  changed_when: false

- name: Download Telegraf package via URL [Debian/Ubuntu]
  command: curl -o /tmp/telegraf-ansible-download.deb {{ telegraf_install_url }}
  when: telegraf_install_url is defined and telegraf_install_url

- name: Install downloaded Telegraf package [Debian/Ubuntu]
  apt:
    deb: /tmp/telegraf-ansible-download.deb
    state: present
  when: telegraf_install_url is defined and telegraf_install_url
