---
- include_tasks: install-redhat.yml
  when: telegraf_install_s3_path == None and ansible_os_family == "RedHat"

- include_tasks: install-debian.yml
  when: telegraf_install_s3_path == None and ansible_os_family == "Debian"

- include_tasks: install-rpm.yml
  when: telegraf_install_s3_path != None
